version: '3.8'

services:
  server:
    container_name: friendzone-server
    image: friendzone-app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_USER=friendzone
      - DB_PASSWORD=admin
      - DB_NAME=friendzone
      - DB_PORT=3306
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: friendzone-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: friendzone
      MYSQL_USER: friendzone
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
